[tool.poetry]
name = "unchecked-transcript"
version = "0.1.0"
description = ""
authors = ["Peter Murray <jester@dltj.org>"]
readme = "README.md"
packages = [{include = "unchecked_transcript"}]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.3"
boto3 = "^1.24.81"


[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
